export enum ChangePasswordActionType {
  CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED",
  CHANGE_PASSWORD_RESET = "CHANGE_PASSWORD_RESET",
}
