export enum ForgotPasswordActionType {
  FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_FAILED = "FORGOT_PASSWORD_FAILED",
  FORGOT_PASSWORD_RESET = "FORGOT_PASSWORD_RESET",
}
