export enum GetAllMainCategoryActionType {
    GET_MAIN_CATEGORY_SUCCESS = "GET_MAIN_CATEGORY_SUCCESS",
    GET_MAIN_CATEGORY_FAILED = "GET_MAIN_CATEGORY_FAILED",
    GET_MAIN_CATEGORY_RESET = "GET_MAIN_CATEGORY_RESET",
  }
