export enum GetAllProductsActionType {
    GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS",
    GET_ALL_PRODUCTS_FAILED = "GET_ALL_PRODUCTS_FAILED",
    GET_ALL_PRODUCTS_RESET = "GET_ALL_PRODUCTS_RESET",
  }
  