export enum GetAddressListActionType {
  GET_ADDRESS_LIST_SUCCESS = "GET_ADDRESS_LIST_SUCCESS",
  GET_ADDRESS_LIST_FAILED = "GET_ADDRESS_LIST_FAILED",
  GET_ADDRESS_LIST_RESET = "GET_ADDRESS_LIST_RESET",
}
