export enum GetCardInfoListActionType {
  GET_CARD_INFO_LIST_SUCCESS = "GET_CARD_INFO_LIST_SUCCESS",
  GET_CARD_INFO_LIST_FAILED = "GET_CARD_INFO_LIST_FAILED",
  GET_CARD_INFO_LIST_RESET = "GET_CARD_INFO_LIST_RESET",
}
