export enum GetCategoryListMenu {
    GET_ALL_CATEGORY_LIST_SUCCESS = "GET_ALL_CATEGORY_LIST_SUCCESS",
    GET_ALL_CATEGORY_LIST_FAILED = " GET_ALL_CATEGORY_LIST_FAILED",
    GET_ALL_CATEGORY_LIST_RESET = " GET_ALL_CATEGORY_LIST_RESET",
  }