export enum RemoveCardInfoActionType {
  REMOVE_CARD_INFO_SUCCESS = "REMOVE_CARD_INFO_SUCCESS",
  REMOVE_CARD_INFO_FAILED = "REMOVE_CARD_INFO_FAILED",
  REMOVE_CARD_INFO_RESET = "REMOVE_CARD_INFO_RESET",
}
